version: '2.3'

services:
  searx:
    container_name: searx
    image: searx/searx:latest
    restart: always
    environment:
      - IMAGE_PROXY=true
      - BASE_URL=https://searx.likkle.monster
      - UID=4244
      - GID=4241
    networks:
      - web
    labels:
       - "traefik.frontend.rule=Host:searx.likkle.monster"
       - "traefik.port=8080"
       - "traefik.backend=searx"
       - "traefik.frontend.entryPoints=http,https"
       - "traefik.docker.network=web"

networks:
  web:
    external: true
